from user import User

juanAccount = User(12345, "Juan Sanchez")
mariaAccount = User(55555, "Maria Diaz ")
gabrielaAccount = User(77777, "Gabriela Lopez")

#print(User.allUsersAccount)
# juanAccount.deposit(100)
# juanAccount.deposit(100)
# juanAccount.deposit(100)
# juanAccount.make_withdrawal(200.0)
# juanAccount.display_User_Balance()
juanAccount.deposit(100).deposit(100).deposit(100).make_withdrawal(200.0).display_User_Balance()
# mariaAccount.deposit(200)
# mariaAccount.deposit(200)
# mariaAccount.make_withdrawal(100.0)
# mariaAccount.make_withdrawal(100.0)
# mariaAccount.display_User_Balance()
mariaAccount.deposit(200).deposit(200).make_withdrawal(100.0).make_withdrawal(100.0).display_User_Balance()
# gabrielaAccount.deposit(1000)
# gabrielaAccount.make_withdrawal(100.0)
# gabrielaAccount.make_withdrawal(100.0)
# gabrielaAccount.make_withdrawal(100.0)
# gabrielaAccount.display_User_Balance()
gabrielaAccount.deposit(1000).make_withdrawal(100.0).make_withdrawal(100.0).make_withdrawal(100.0).display_User_Balance()
# gabrielaAccount.transfer_Money( juanAccount, 200.0)
# gabrielaAccount.display_User_Balance()
# juanAccount.display_User_Balance()
gabrielaAccount.transfer_Money(juanAccount, 200.0).display_User_Balance()
juanAccount.display_User_Balance()